version: "3"
services:
  zookeeper-local:
    container_name: zookeeper-local
    image: zookeeper:3.4.14
    ports:
      - "2181:2181"
  kafka-local:
    container_name: kafka-local
    image: wurstmeister/kafka:2.12-2.2.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ADVERTISED_HOST_NAME: kafka-local
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181
      KAFKA_NUM_PARTITIONS: 3
    depends_on:
      - zookeeper-local
  cassandra-local:
    container_name: cassandra-local
    image: cassandra:3.11.5
    ports:
      - "9042:9042"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    environment:
      MAX_HEAP_SIZE: 256M
      HEAP_NEWSIZE: 24M
  oracle-local:
    image: wnameless/oracle-xe-11g-r2
    ports:
      - "1521:1521"
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - USERNAME=admin
      - PASSWORD=qwe123
  kafka-manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    depends_on:
      - zookeeper-local
      - kafka-local
    ports:
      - "9000:9000"
    expose:
      - 9000
    environment:
      ZK_HOSTS: zookeeper-local:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    command: -Dpidfile.path=/dev/null
  zkui-local:
    image: qnib/zkui
    depends_on:
      - zookeeper-local
    ports:
      - "9090:9090"
    expose:
      - 9090
    environment:
      ZK_SERVER: zookeeper-local:2181
  mongo-local:
    image: mongo:3.4.9
    ports:
      - "27017:27017"
      - "28017:28017"
