eventapis:
  storeConfig:
    contactPoints: localhost:9042
    keyspaceName: test
    username: cassandra
    password: cassandra
  eventRecords:
    order: orderevents
  eventBus:
    bootstrapServers: localhost:9092
    consumer:
      groupId: ${info.build.artifact}

server:
  port: 8160

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

payment-client-url: http://localhost:8164
