eventapis:
  storeConfig:
    contactPoints: dbtest.n11pro.n11.local:9042
    keyspaceName: test
    username: test_order
    password: qwe123
  eventRecords:
    stock: stockevents
  eventBus:
    bootstrapServers: localhost:9092
    consumer:
      groupId: ${info.build.artifact}
spring:
  datasource:
    url: jdbc:oracle:thin:@test-api:1521:xe
    username: TEST_ORDER
    password: qwe123
    platform: ORACLE
    tomcat:
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      initial-size: 2
      min-idle: 1
      max-idle: 4
      max-active: 8
      max-wait: 3000
      min-evictable-idle-time-millis: 60000
      log-abondoned: true
      log-validation-errors: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8162


