eventapis:
  storeConfig:
    contactPoints: localhost:9042
    keyspaceName: test
    #    username: test_order
    username: cassandra
    #    password: qwe123
    password: cassandra
  eventRecords:
    payment: paymentevents
  eventBus:
    bootstrapServers: localhost:9092
#    clientId: ${project.artifactId}
    consumer:
      groupId: ${info.build.artifact}

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: TEST_ORDER
    password: qwe123
    platform: ORACLE
    tomcat:
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      initial-size: 2
      min-idle: 1
      max-idle: 4
      max-active: 8
      max-wait: 3000
      min-evictable-idle-time-millis: 60000
      log-abondoned: true
      log-validation-errors: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8164


