server:
  port: 7800
  jetty:
    acceptors: 2
service:
  name: Eventapis Operation Center

eventapis:
  eventBus:
    bootstrapServers: localhost:9092
    zookeeperServers: localhost:2181
    consumer:
      groupId: ${info.build.artifact}
    consumerGroupRegex: "^(.+-service)$"

emon:
  hazelcast:
    discovery:
      type: multicast
      multicast:
        multicastGroup: 224.0.0.1
        multicastPort: 54327
        multicastTimeToLive: 15
        multicastTimeoutSeconds: 5
#        trustedInterfaces: localhost,127.0.0.1
        loopbackModeEnabled: true
    interfaces:
      enabled: true
      interfaces: 127.0.0.1
    group:
      name: emon
      password: emon123
  listenTopology:
    enabled: true
  offsetScheduler:
    enabled: true

